name: Build and Unit Test

on: pull_request

jobs:
  matlab:
    name: Matlab build and unit test
    runs-on: ubuntu-18.04
    env:
      CC: gcc-7
      CXX: g++-7

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
     
      - name: Install Pulseq-CEST
        uses: matlab-actions/run-command@v1
        with:
          command: install_pulseqcest; 

      - name: Build and Unit tests
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(genpath(pwd)); compile_pulseqcest; cd tests; testResults = runtests(); assert(nnz([testResults.Failed])==0);
          
